# Generated by Django 5.0.6 on 2024-07-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Начало рассылки')),
                ('end_date', models.DateTimeField(verbose_name='Конец рассылки')),
                ('interval', models.CharField(choices=[('once', 'разовая'), ('daily', 'ежедневно'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='once', max_length=10, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('active', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=10, verbose_name='Статус')),
                ('is_active', models.BooleanField(choices=[(True, 'Активна'), (False, 'Неактивна')], default=True, verbose_name='Активность')),
                ('sending_to', models.ManyToManyField(to='app_customers.customers', verbose_name='Адресат')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mailings.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
